blueprint:
  name: Motion-activated Light with Time-based Brightness
  description: >
    Turn on lights/switches on motion/occupancy, with optional conditions and
    brightness automatically adjusted by time ranges that you can edit on the fly.
  domain: automation
  input:
    motion_sensors:
      name: Motion and Occupancy Sensors
      description: Select one or more motion or occupancy sensors.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
          multiple: true

    entity_target:
      name: Lights and Switches
      description: Select lights/switches (entity, device, area, or label).
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    no_motion_wait:
      name: Wait Time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    # Tranche horaire 1
    time_range_1_enabled:
      name: Tranche 1 - Activer
      description: Activer ou désactiver l'allumage durant la tranche 1
      default: true
      selector:
        boolean:

    time_range_1_start:
      name: Tranche 1 - Heure de début
      description: Heure de début de la tranche 1 (format HH:MM)
      default: "00:00"
      selector:
        time:

    time_range_1_end:
      name: Tranche 1 - Heure de fin
      description: Heure de fin de la tranche 1 (format HH:MM)
      default: "06:00"
      selector:
        time:

    time_range_1_mode:
      name: Tranche 1 - Mode
      description: Choisir entre couleur+luminosité ou scène
      default: color
      selector:
        select:
          options:
            - label: Couleur + Luminosité
              value: color
            - label: Scène
              value: scene

    time_range_1_brightness:
      name: Tranche 1 - Luminosité
      description: Luminosité pour la tranche 1 (0-255)
      default: 10
      selector:
        number:
          min: 0
          max: 255

    time_range_1_color:
      name: Tranche 1 - Couleur
      description: Couleur pour la tranche 1 (format RGB)
      default: [255, 220, 180]
      selector:
        color_rgb:

    time_range_1_scene:
      name: Tranche 1 - Scène
      description: Scène à activer pour la tranche 1
      default: ""
      selector:
        entity:
          domain: scene

    # Tranche horaire 2
    time_range_2_enabled:
      name: Tranche 2 - Activer
      description: Activer ou désactiver l'allumage durant la tranche 2
      default: true
      selector:
        boolean:

    time_range_2_start:
      name: Tranche 2 - Heure de début
      description: Heure de début de la tranche 2 (format HH:MM)
      default: "06:00"
      selector:
        time:

    time_range_2_end:
      name: Tranche 2 - Heure de fin
      description: Heure de fin de la tranche 2 (format HH:MM)
      default: "22:00"
      selector:
        time:

    time_range_2_mode:
      name: Tranche 2 - Mode
      description: Choisir entre couleur+luminosité ou scène
      default: color
      selector:
        select:
          options:
            - label: Couleur + Luminosité
              value: color
            - label: Scène
              value: scene

    time_range_2_brightness:
      name: Tranche 2 - Luminosité
      description: Luminosité pour la tranche 2 (0-255)
      default: 255
      selector:
        number:
          min: 0
          max: 255

    time_range_2_color:
      name: Tranche 2 - Couleur
      description: Couleur pour la tranche 2 (format RGB)
      default: [255, 255, 255]
      selector:
        color_rgb:

    time_range_2_scene:
      name: Tranche 2 - Scène
      description: Scène à activer pour la tranche 2
      default: ""
      selector:
        entity:
          domain: scene

    # Tranche horaire 3
    time_range_3_enabled:
      name: Tranche 3 - Activer
      description: Activer ou désactiver l'allumage durant la tranche 3
      default: true
      selector:
        boolean:

    time_range_3_start:
      name: Tranche 3 - Heure de début
      description: Heure de début de la tranche 3 (format HH:MM)
      default: "22:00"
      selector:
        time:

    time_range_3_end:
      name: Tranche 3 - Heure de fin
      description: Heure de fin de la tranche 3 (format HH:MM)
      default: "23:59"
      selector:
        time:

    time_range_3_mode:
      name: Tranche 3 - Mode
      description: Choisir entre couleur+luminosité ou scène
      default: color
      selector:
        select:
          options:
            - label: Couleur + Luminosité
              value: color
            - label: Scène
              value: scene

    time_range_3_brightness:
      name: Tranche 3 - Luminosité
      description: Luminosité pour la tranche 3 (0-255)
      default: 30
      selector:
        number:
          min: 0
          max: 255

    time_range_3_color:
      name: Tranche 3 - Couleur
      description: Couleur pour la tranche 3 (format RGB)
      default: [255, 180, 100]
      selector:
        color_rgb:

    time_range_3_scene:
      name: Tranche 3 - Scène
      description: Scène à activer pour la tranche 3
      default: ""
      selector:
        entity:
          domain: scene

    condition_entity:
      name: Condition Entity (Optional)
      description: >
        Select an entity to check its state (optional).
        If no entity is defined, this condition is not evaluated.
      default:
      selector:
        entity:

    condition_states:
      name: Allowed States for Condition Entity
      description: >
        Enter the states that the condition entity should be in (comma-separated).
        If a Condition Entity is not defined these values are ignored.
      default:
      selector:
        text:

    sun_condition:
      name: Sun Condition (Optional)
      description: Select the sun condition to check.
      default: none
      selector:
        select:
          options:
            - none
            - day
            - night

    sun_offset:
      name: Sun Offset (Optional)
      description: Offset from sunrise/sunset in format 'HH:MM' (e.g., '01:00' or '-01:00')
      default: "00:00"
      selector:
        text:

    blocking_entity:
      name: Blocking Entity (Optional)
      description: >
        Select an entity that will prevent the automation from running
        when in specified states.
      default:
      selector:
        entity:

    blocking_states:
      name: Blocking States
      description: Enter the states that will prevent the automation from running (comma-separated).
      default:
      selector:
        text:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

variables:
  condition_entity: !input condition_entity
  condition_states: !input condition_states
  sun_condition: !input sun_condition
  sun_offset: !input sun_offset
  blocking_entity: !input blocking_entity
  blocking_states: !input blocking_states
  entity_target: !input entity_target

  # Tranches horaires
  tr1_enabled: !input time_range_1_enabled
  tr1_start: !input time_range_1_start
  tr1_end: !input time_range_1_end
  tr1_mode: !input time_range_1_mode
  tr1_brightness: !input time_range_1_brightness
  tr1_color: !input time_range_1_color
  tr1_scene: !input time_range_1_scene
  
  tr2_enabled: !input time_range_2_enabled
  tr2_start: !input time_range_2_start
  tr2_end: !input time_range_2_end
  tr2_mode: !input time_range_2_mode
  tr2_brightness: !input time_range_2_brightness
  tr2_color: !input time_range_2_color
  tr2_scene: !input time_range_2_scene
  
  tr3_enabled: !input time_range_3_enabled
  tr3_start: !input time_range_3_start
  tr3_end: !input time_range_3_end
  tr3_mode: !input time_range_3_mode
  tr3_brightness: !input time_range_3_brightness
  tr3_color: !input time_range_3_color
  tr3_scene: !input time_range_3_scene

  # Vérifier si on doit allumer selon la tranche horaire actuelle
  should_turn_on: >-
    {% set now_time = now().strftime('%H:%M') %}
    {% if tr1_start <= now_time < tr1_end %}
      {{ tr1_enabled }}
    {% elif tr2_start <= now_time < tr2_end %}
      {{ tr2_enabled }}
    {% elif tr3_start <= now_time < tr3_end %}
      {{ tr3_enabled }}
    {% else %}
      false
    {% endif %}

  # Mode actuel (color ou scene) selon la tranche horaire
  current_mode: >-
    {% set now_time = now().strftime('%H:%M') %}
    {% if tr1_start <= now_time < tr1_end %}
      {{ tr1_mode }}
    {% elif tr2_start <= now_time < tr2_end %}
      {{ tr2_mode }}
    {% elif tr3_start <= now_time < tr3_end %}
      {{ tr3_mode }}
    {% else %}
      none
    {% endif %}

  # Brightness automatiquement choisie selon l'heure actuelle
  calculated_brightness: >-
    {% set now_time = now().strftime('%H:%M') %}
    {% if tr1_start <= now_time < tr1_end %}
      {{ tr1_brightness | int }}
    {% elif tr2_start <= now_time < tr2_end %}
      {{ tr2_brightness | int }}
    {% elif tr3_start <= now_time < tr3_end %}
      {{ tr3_brightness | int }}
    {% else %}
      0
    {% endif %}

  # Couleur automatiquement choisie selon l'heure actuelle
  calculated_color: >-
    {% set now_time = now().strftime('%H:%M') %}
    {% if tr1_start <= now_time < tr1_end %}
      {{ tr1_color }}
    {% elif tr2_start <= now_time < tr2_end %}
      {{ tr2_color }}
    {% elif tr3_start <= now_time < tr3_end %}
      {{ tr3_color }}
    {% else %}
      [255, 255, 255]
    {% endif %}

  # Scène automatiquement choisie selon l'heure actuelle
  calculated_scene: >-
    {% set now_time = now().strftime('%H:%M') %}
    {% if tr1_start <= now_time < tr1_end %}
      {{ tr1_scene }}
    {% elif tr2_start <= now_time < tr2_end %}
      {{ tr2_scene }}
    {% elif tr3_start <= now_time < tr3_end %}
      {{ tr3_scene }}
    {% else %}
      
    {% endif %}

condition:
  - condition: and
    conditions:
      # Vérifier si l'allumage est autorisé pour la tranche horaire actuelle
      - condition: template
        value_template: "{{ should_turn_on }}"

      # Blocking entity (do not run if in one of the blocking states)
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ blocking_entity == None or blocking_entity == '' }}"
          - condition: template
            value_template: >
              {% set blocking_states_list = blocking_states.split(',') | map('trim') | list %}
              {{ states(blocking_entity) not in blocking_states_list }}

      # Optional condition entity (must be in one of allowed states)
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ condition_entity == None or condition_entity == '' }}"
          - condition: template
            value_template: >
              {% set states_list = condition_states.split(',') | map('trim') | list %}
              {{ condition_entity != None and condition_entity != '' and states_list | length > 0 and states(condition_entity) in states_list }}

      # Optional sun condition
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ sun_condition == 'none' }}"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ sun_condition == 'day' }}"
              - condition: sun
                after: sunrise
                after_offset: !input sun_offset
                before: sunset
                before_offset: !input sun_offset
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ sun_condition == 'night' }}"
              - condition: or
                conditions:
                  - condition: sun
                    after: sunset
                    after_offset: !input sun_offset
                  - condition: sun
                    before: sunrise
                    before_offset: !input sun_offset

action:
  - choose:
      # Si le mode est "scene", activer la scène
      - conditions:
          - condition: template
            value_template: "{{ current_mode == 'scene' and calculated_scene != '' }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: "{{ calculated_scene }}"
      
      # Si le mode est "color", utiliser la couleur + brightness de la tranche horaire
      - conditions:
          - condition: template
            value_template: "{{ current_mode == 'color' }}"
        sequence:
          # Allumer les lumières avec couleur et brightness (s'applique aux lights du target)
          - service: light.turn_on
            target: !input entity_target
            data:
              brightness: "{{ calculated_brightness }}"
              rgb_color: "{{ calculated_color }}"
          # Allumer les switches du target
          - service: switch.turn_on
            target: !input entity_target

  - wait_for_trigger:
      platform: state
      entity_id: !input motion_sensors
      to: "off"

  - delay: !input no_motion_wait

  # Éteindre les lumières et switches
  - service: homeassistant.turn_off
    target: !input entity_target
